### ISSUE TITLE
Unable to run make

### ISSUE THREAD

**Issue by trahma** [prometheus/pushgateway#35] opened 2015-04-30 02:55 UTC
Attempting to run make on ubuntu 14.04 or in an OSX prompt, I'm getting the following error:
```
GOROOT=/home/vagrant/pushgateway/.deps/go GOPATH=/home/vagrant/pushgateway/.deps/gopath /home/vagrant/pushgateway/.deps/go/bin/go get -d
package bitbucket.org/ww/goautoneg
	imports code.google.com/p/goprotobuf/proto: unable to detect version control system for code.google.com/ path
make: *** [dependencies] Error 1
vagrant@vagrant-ubuntu-trusty-64:~/pushgateway$
```

I'm unfamiliar with Go but attempted to install the Go package from golang.org which also didn't seem to help.  Base prometheus however installed fine on both my vagrant machine and my mbp.

**Comment by juliusv** [comment] 2015-04-30 08:58
Thanks for reporting! Should be fixed by https://github.com/prometheus/pushgateway/pull/36.

**Closed by juliusv** 2015-04-30 08:58 UTC

**Comment by jcftang** [comment] 2015-05-26 06:29
It looks like there might still be something missing

```
jtang@awesome-o-w:[(none)@master]pushgateway$ make
GOROOT=/Users/jtang/develop/pushgateway/.deps/go GOPATH=/Users/jtang/develop /Users/jtang/develop/pushgateway/.deps/go/bin/go get -d
GOROOT=/Users/jtang/develop/pushgateway/.deps/go GOPATH=/Users/jtang/develop /Users/jtang/develop/pushgateway/.deps/go/bin/go get github.com/jteeuwen/go-bindata/...
/Users/jtang/develop/bin/go-bindata resources/
make: /Users/jtang/develop/bin/go-bindata: No such file or directory
make: *** [bindata.go] Error 1
jtang@awesome-o-w:[(none)@master]pushgateway$ git describe
fatal: No annotated tags can describe 'eefacc22c6a9b6393dde154804d65094cd54b3ed'.
However, there were unannotated tags: try --tags.
```

**Comment by beorn7** [comment] 2015-05-26 08:28
@jcftang I think you found out how to reproduce https://github.com/prometheus/pushgateway/issues/37  (which I thought is fixed). Thanks for that. :)

See there for further progress.
