### ISSUE TITLE
3x regression in memory usage

### ISSUE THREAD

**Issue by belm0** [prometheus/pushgateway#363] opened 2020-07-31 02:33 UTC
## Bug Report
**What did you do?**
Upgraded from pushgateway v0.8.0 to v1.2.0

**What did you expect to see?**
Reasonably same CPU and memory usage.

**What did you see instead? Under which circumstances?**
3x memory usage at steady state (190MB vs. 65MB)

there are about 500k active metrics held by the pushgateway

![Screen Shot 2020-07-31 at 11 27 19 AM](https://user-images.githubusercontent.com/1708631/88993623-6d56ad80-d321-11ea-8964-a3323e4dc315.png)

**Environment**

* System information:

`Linux 4.14.138+ x86_64`

* Pushgateway version:

v1.2.0

* Pushgateway command line:

`pushgateway --push.disable-consistency-check`

**Comment by beorn7** [comment] 2020-08-05 13:58
See #313.

**Comment by belm0** [comment] 2020-08-06 00:36
@beorn7 I'm familiar with the cited issue and participated in it.  I don't see the relation to the memory regression.

In our deployment, memory use does not appear correlated to the push rate.  This seems like a regression in memory efficiency per metric.

**Comment by beorn7** [comment] 2020-08-06 11:01
Sorry, now I see that you had already disabled the consistency check.

I haven't seen such a regression in any of my production setups. Could you do heap profiling on your Pushgateway to find out where the memory is consumed?

Wild guess is that it has something to do with the new API to query pushed metrics. It might need to allocate scratch space to serve all of them. That usually doesn't make a dent because the PGW is not meant to serve thousands of metrics, not to speak about hundreds of thousands of metrics.

**Comment by belm0** [comment] 2020-08-07 03:41
I tried v1.1.0 and observed the same memory use.

Offhand I don't know how to heap profile the pushgateway.

**Comment by beorn7** [comment] 2021-02-19 17:40
I'll close this for lack of follow up. If you can provide a heap profile or any other further evidence that might help to track this down, feel free to follow up.

**Closed by beorn7** 2021-02-19 17:40 UTC
Labels: enhancement, help wanted
