### ISSUE TITLE
Continuously push multiple batch to pushgateway may cause data loss

### ISSUE THREAD

**Issue by lylex** [prometheus/pushgateway#308] opened 2019-10-27 13:37 UTC
## Bug Report
**What did you do?**

I want to use curl to push some metrics to promethues via pushgateway, like this:

```
cat <<EOF | curl -v --data-binary @- http://127.0.0.1:9091/metrics/job/pushgateway
bad_fator_wight{id="11137241"} 3.20
bad_fator_wight{id="13010551"} 6.03
...
bad_fator_wight{id="11244135"} 5.30
EOF
```

The data could be about 300KB, and there might be 3 or more batches to be pushed in a very short time.

**What did you expect to see?**

All the metrics data from all the 3 batches is fed into prometheus.

**What did you see instead? Under which circumstances?**

I saw much data from the first batch are lost from prometheus. I suspect pushgateway drop the data.

**Environment**

    I used the prom/pushgateway:v1.0.0 docker image

* System information:

    The docker host system, Linux 4.14.104-95.84.amzn2.x86_64 x86_64

* Pushgateway version:

    v1.0.0

* Pushgateway command line:

	N/A

* Logs:

    N/A

**Comment by snebel29** [comment] 2019-10-27 21:50
Hi @lylex ,
It's hard to say without having a reproducible scenario of what you're doing exactly, I've created one using my best understanding of what you describe, also note that I'm not an official maintainer of this repository.

Run Pushgateway:
```
docker run -p 9091:9091 prom/pushgateway:v1.0.0
```
Then execute 3 simple "batches" of the same metric name but with a different grouping key by `id`:
```
curl -s http://localhost:9091/metrics | egrep -v '^#' | grep bad_fator_wight | wc -l

cat <<EOF | curl -XPUT -v --data-binary @- http://127.0.0.1:9091/metrics/job/pushgateway
bad_fator_wight{id="1"} 3.20
bad_fator_wight{id="2"} 6.03
bad_fator_wight{id="3"} 5.30
EOF

curl -s http://localhost:9091/metrics | egrep -v '^#' | grep bad_fator_wight | wc -l

cat <<EOF | curl -XPUT -v --data-binary @- http://127.0.0.1:9091/metrics/job/pushgateway
bad_fator_wight{id="4"} 3.20
bad_fator_wight{id="5"} 6.03
bad_fator_wight{id="6"} 5.30
EOF

curl -s http://localhost:9091/metrics | egrep -v '^#' | grep bad_fator_wight | wc -l

cat <<EOF | curl -XPUT -v --data-binary @- http://127.0.0.1:9091/metrics/job/pushgateway
bad_fator_wight{id="7"} 3.20
bad_fator_wight{id="8"} 6.03
bad_fator_wight{id="9"} 5.30
EOF

curl -s http://localhost:9091/metrics | egrep -v '^#' | grep bad_fator_wight | wc -l
```
As you can see from the results, output: `3` of my experiment the last batch seems to be replacing completely the old one even when the new metrics have a different `id` label which should produce a unique grouping key, I've also tried with old versions like `v0.5.0` which is more than a year old and the result is the same.

Could this be what you're experiencing?

I will try to dig some more tomorrow,

**Comment by snebel29** [comment] 2019-10-27 22:47
I took a look to the code and re-read the documentation and here is what I found:

1. The grouping key is created using the labels from the URI pathonly, labels specified in between brackets seems to be persisted by the write operation but not used to compute the grouping key, the examples in the documentation does not state this clearly but I think can be inferred from the examples.
2. The curl + heredoc example that you are using uses different metric names, never the same metric name, again a hint on correct usage.

I think this is a bit confusing but probably expected behavior, using the information provided above you could change the way you are pushing your metrics to get them all-in, for example:

```
curl -s http://localhost:9091/metrics | egrep -v '^#' | grep bad_fator_wight | wc -l

cat <<EOF | curl -XPUT -v --data-binary @- http://127.0.0.1:9091/metrics/job/pushgateway/id/1
bad_fator_wight 3.20
EOF

curl -s http://localhost:9091/metrics | egrep -v '^#' | grep bad_fator_wight | wc -l

cat <<EOF | curl -XPUT -v --data-binary @- http://127.0.0.1:9091/metrics/job/pushgateway/id/2
bad_fator_wight 3.20
EOF

curl -s http://localhost:9091/metrics | egrep -v '^#' | grep bad_fator_wight | wc -l

cat <<EOF | curl -XPUT -v --data-binary @- http://127.0.0.1:9091/metrics/job/pushgateway/id/3
bad_fator_wight 3.20
EOF

curl -s http://localhost:9091/metrics | egrep -v '^#' | grep bad_fator_wight | wc -l
```

There is also the smell that you are probably pushing too many metrics creating a huge cardinality, do you really need to push such a big a mount of time series?

Take a read on https://www.robustperception.io/cardinality-is-key

I hope that helped,

Cheers.

**Comment by beorn7** [comment] 2019-10-28 11:45
Yes, pushing with the same grouping key will replace all metrics in that group that have the same name as metrics you pushed. See https://github.com/prometheus/pushgateway#post-method

You have to push to different groups if you want to push metrics of the same name in different batches. However, you should also consider if you are perhaps using the Pushgateway for something it was not intended for. See https://prometheus.io/docs/practices/pushing/ .

As this is not a bug but a usage question, I'll close this issue. It makes more sense to ask usage questions on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Closed by beorn7** 2019-10-28 11:45 UTC
