### ISSUE TITLE
Concurrent map iteration and map write in GetMetricFamiliesMap

### ISSUE THREAD

**Issue by chenbiaoit** [prometheus/pushgateway#401] opened 2021-04-21 06:16 UTC
We registered a large number of tasks in PushGateway. The following error occurred during the use process. Could you please tell us the reason?

-----
**fatal error: concurrent map iteration and map write**

goroutine 35 [running]:
runtime.throw(0xa817fa, 0x26)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc00243fa90 sp=0xc00243fa60 pc=0x438132
runtime.mapiternext(0xc00243fb90)
        /usr/local/go/src/runtime/map.go:858 +0x54c fp=0xc00243fb10 sp=0xc00243fa90 pc=0x410cac
github.com/prometheus/pushgateway/storage.(*DiskMetricStore).GetMetricFamiliesMap(0xc000410060, 0x0)
        /root/workspace/src/github.com/prometheus/pushgateway/storage/diskmetricstore.go:199 +0x12b fp=0xc00243fc70 sp=0xc00243fb10 pc=0x934acb
github.com/prometheus/pushgateway/storage.(*DiskMetricStore).checkWriteRequest(0xc000410060, 0xc00220f800, 0xc017672c70bf061c, 0xf88422941c6c, 0x10186e0, 0xc00220f860, 0x0, 0xc000265380, 0x0)
        /root/workspace/src/github.com/prometheus/pushgateway/storage/diskmetricstore.go:377 +0x1b7 fp=0xc00243fdb0 sp=0xc00243fc70 pc=0x935fb7
github.com/prometheus/pushgateway/storage.(*DiskMetricStore).loop(0xc000410060, 0x45d964b800)
        /root/workspace/src/github.com/prometheus/pushgateway/storage/diskmetricstore.go:235 +0x2d7 fp=0xc00243ffd0 sp=0xc00243fdb0 pc=0x935057
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00243ffd8 sp=0xc00243ffd0 pc=0x4717c1
created by github.com/prometheus/pushgateway/storage.NewDiskMetricStore
        /root/workspace/src/github.com/prometheus/pushgateway/storage/diskmetricstore.go:104 +0x1e6

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fb75cf4ef98, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00021e398, 0x72, 0x0, 0x0, 0xa6ccd6)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00021e380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc00021e380, 0x9f515ddd4b97a5d6, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc000458c90, 0x607d2531, 0xc000489838, 0x4c7846)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000458c90, 0xc000489888, 0x18, 0xc000000180, 0x6a905b)
        /usr/local/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc0004340e0, 0xccb390, 0xc000458c90, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2981 +0x285
github.com/prometheus/exporter-toolkit/web.Serve(0xccb390, 0xc000458c90, 0xc0004340e0, 0x0, 0x0, 0xcc1fc0, 0xc00040c540, 0x0, 0xc00040c540)
        /root/go/pkg/mod/github.com/prometheus/exporter-toolkit@v0.5.1/web/tls_config.go:192 +0x1b0
main.main()
        /root/workspace/src/github.com/prometheus/pushgateway/main.go:199 +0x3868

goroutine 7 [syscall, 4554 minutes]:
os/signal.signal_recv(0xc000410180)
        /usr/local/go/src/runtime/sigqueue.go:168 +0xa5
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x45

**Comment by chenbiaoit** [comment] 2021-04-21 07:15
v1.4.0

**Comment by beorn7** [comment] 2021-04-21 21:07
Thanks for reporting. This should not happen. We have to investigate…

(Weirdly, #96 looks similar, but it's ancient and was closed immediately back then.)

**Comment by chenbiaoit** [comment] 2021-04-22 02:52
> Thanks for reporting. This should not happen. We have to investigate…
> 
> (Weirdly, #96 looks similar, but it's ancient and was closed immediately back then.)

Yes, thank you very much and I look forward to your reply

**Comment by chenbiaoit** [comment] 2021-04-23 10:50
In the presence of blocking high concurrency, can will "NameToTimestampedMetricFamilyMap" replacement for concurrent - a map?

Such as:
https://github.com/orcaman/concurrent-map

**Comment by chenbiaoit** [comment] 2021-04-23 10:52
In the presence of blocking high concurrency, can will "NameToTimestampedMetricFamilyMap" replacement 
for "concurrent-map"?

Such as:
https://github.com/orcaman/concurrent-map

**Comment by beorn7** [comment] 2021-05-26 20:44
> In the presence of blocking high concurrency, can will "NameToTimestampedMetricFamilyMap" replacement
for "concurrent-map"?

If someone wants to do the work to optimize the code for high concurrency, and if those optimizations don't make the code perform worse for the intended use case of the Pushgateway, then PRs are welcome.

**Comment by beorn7** [comment] 2021-05-26 21:06
Coming back to the issue at hand: 

I failed to find any path that would allow the concurrent write request you have seen in your error message. The stack trace only has a reading goroutine but no goroutine that would write to the map. Is the stack trace perhaps incomplete?

**Comment by dgl** [comment] 2021-05-27 18:52
I had a quick go at reproducing this with brute force, I built pushgateway with race detection (`go build -race`) and enabled persistence very frequently: `./pushgateway --persistence.file=persist --persistence.interval=1ms`

Then I continually pushed data at it, with around 4000 groups:
```
while true; do x=$[x+1]; curl -d "# HELP x test
# TYPE x gauge
x $RANDOM
" localhost:9091/metrics/job/foo/instance/i$[x % 4000]; done
```

I tried this on macOS, on a laptop, so not many cores.

In addition to the question about the stacktrace from Björn it would be useful to know some more details like pushgateway version, OS, how much data is in pushgateway, size of the persistence file, specs of the server, etc.

**Comment by beorn7** [comment] 2021-05-27 19:17
Thanks for investigating, @dgl . Would be cool to get to the bottom of this.

PGW version was v1.4.0 (from what was mentioned above).

**Comment by beorn7** [comment] 2021-06-09 12:24
Despite a lot of efforts, we could not reproduce this behavior. The most reasonable explanation so far seems to be that @chenbiaoit accidentally ran a modified version of the Pushgateway (perhaps from an experiment to improve performance during high concurrency?).

I'll close this for now, but anyone seeing this, please follow up here with traces or any other hints.

**Closed by beorn7** 2021-06-09 12:24 UTC
Labels: bug, critical, help wanted
