### ISSUE TITLE
Connection status abnormal

### ISSUE THREAD

**Issue by kakaNo1** [prometheus/pushgateway#388] opened 2021-02-19 07:04 UTC
## Feature request
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
 curl -XGET http://localhost:9091/-/ready
write queue is full

lsof -p 17422 | wc -l
2265
17422 is PushGateway's PID

**What did you expect to see?**

**What did you see instead? Under which circumstances?**
Allow some time and the client will report 502/504
**Environment**

* System information:

		Insert output of `uname -srm` here. Linux 3.10.0-1062.12.1.el7.x86_64 x86_64

* Pushgateway version:

		Insert output of `pushgateway --version` here.
pushgateway, version 1.2.0 (branch: HEAD, revision: b7e0167e9574f4f88404dde9653ee1d3c940f2eb)
  build user:       root@0e823ccfff84
  build date:       20200311-18:51:01
  go version:       go1.13.8

* Pushgateway command line:

		Insert full command line.
/data/services/pushgateway-1.2.0.linux-amd64/pushgateway --web.listen-address=:9091 --web.enable-admin-api

* Logs:
```
Insert Pushgateway logs relevant to the issue here.

Feb 19 14:53:04 iZ4i1fzp7tazf9Z pushgateway[17422]: level=error ts=2021-02-19T06:53:04.803Z caller=main.go:56 msg="error encoding and sending metric family: write tcp 10.0.21.180:9091->100.97.200.196:36240: write: broken pipe\n"
Feb 19 14:53:04 iZ4i1fzp7tazf9Z pushgateway[17422]: 2021/02/19 14:53:04 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:375)
Feb 19 14:53:18 iZ4i1fzp7tazf9Z pushgateway[17422]: level=error ts=2021-02-19T06:53:18.275Z caller=main.go:56 msg="error encoding and sending metric family: write tcp 10.0.21.180:9091->100.97.200.176:21078: write: broken pipe\n"
Feb 19 14:53:18 iZ4i1fzp7tazf9Z pushgateway[17422]: 2021/02/19 14:53:18 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:375)
Feb 19 14:53:39 iZ4i1fzp7tazf9Z pushgateway[17422]: level=error ts=2021-02-19T06:53:39.800Z caller=main.go:56 msg="error encoding and sending metric family: write tcp 10.0.21.180:9091->100.97.200.232:46830: write: broken pipe\n"
Feb 19 14:53:39 iZ4i1fzp7tazf9Z pushgateway[17422]: 2021/02/19 14:53:39 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:375)
Feb 19 14:53:51 iZ4i1fzp7tazf9Z pushgateway[17422]: level=error ts=2021-02-19T06:53:51.489Z caller=main.go:56 msg="error encoding and sending metric family: write tcp 10.0.21.180:9091->100.97.200.189:37384: write: broken pipe\n"
Feb 19 14:53:51 iZ4i1fzp7tazf9Z pushgateway[17422]: 2021/02/19 14:53:51 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:375)
Feb 19 14:54:03 iZ4i1fzp7tazf9Z pushgateway[17422]: level=error ts=2021-02-19T06:54:03.508Z caller=main.go:56 msg="error encoding and sending metric family: write tcp 10.0.21.180:9091->100.97.200.225:14912: write: broken pipe\n"
Feb 19 14:54:03 iZ4i1fzp7tazf9Z pushgateway[17422]: 2021/02/19 14:54:03 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:375)
```

**Comment by kakaNo1** [comment] 2021-02-19 07:07
I looked up connections via lsof -p, which is the most common type of connection:
```
pushgatew 17422 root 2370u     sock                0,7      0t0 13977132 protocol: TCPv6
pushgatew 17422 root 2371u     sock                0,7      0t0 13978782 protocol: TCPv6
pushgatew 17422 root 2372u     sock                0,7      0t0 13977136 protocol: TCPv6
pushgatew 17422 root 2373u     sock                0,7      0t0 13978125 protocol: TCPv6
pushgatew 17422 root 2374u     sock                0,7      0t0 13978149 protocol: TCPv6
pushgatew 17422 root 2375u     sock                0,7      0t0 13976418 protocol: TCPv6
pushgatew 17422 root 2376u     sock                0,7      0t0 13978135 protocol: TCPv6
pushgatew 17422 root 2377u     sock                0,7      0t0 13978137 protocol: TCPv6
pushgatew 17422 root 2378u     sock                0,7      0t0 13978139 protocol: TCPv6
pushgatew 17422 root 2379u     sock                0,7      0t0 13978141 protocol: TCPv6
pushgatew 17422 root 2380u     sock                0,7      0t0 13978790 protocol: TCPv6
pushgatew 17422 root 2381u     sock                0,7      0t0 13978792 protocol: TCPv6
pushgatew 17422 root 2382u     sock                0,7      0t0 13978794 protocol: TCPv6
pushgatew 17422 root 2383u     sock                0,7      0t0 13978796 protocol: TCPv6
pushgatew 17422 root 2384u     sock                0,7      0t0 13978800 protocol: TCPv6
pushgatew 17422 root 2385u     sock                0,7      0t0 13978802 protocol: TCPv6
pushgatew 17422 root 2386u     sock                0,7      0t0 13978808 protocol: TCPv6
pushgatew 17422 root 2387u     sock                0,7      0t0 13978810 protocol: TCPv6
pushgatew 17422 root 2388u     sock                0,7      0t0 13978812 protocol: TCPv6
pushgatew 17422 root 2389u     sock                0,7      0t0 13978818 protocol: TCPv6
pushgatew 17422 root 2390u     sock                0,7      0t0 13978820 protocol: TCPv6
pushgatew 17422 root 2391u     sock                0,7      0t0 13978153 protocol: TCPv6
pushgatew 17422 root 2392u     sock                0,7      0t0 13978157 protocol: TCPv6
```

**Comment by kakaNo1** [comment] 2021-02-20 01:48
Okay, I've added it, so let's watch it.
Another question: I divided PushGatewa into 4 (9091-9094) to deal with a large amount of data, but I don't know if this is reasonable?I would like to see the entry unique, rather than I need to specify a different pushGateway entry separately in my client

**Comment by beorn7** [comment] 2021-02-22 12:56
Sharding the Pushgateway is something you can surely do.

Just as a rule of thumb, if you put that much load on the Pushgateway, the odds are you are using it in a way that it was never meant to.

To discuss usage questions like this, I recommend the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by beorn7** [comment] 2021-02-23 12:41
For now, I assume this is not a bug in Pushgateway but mere overload and close this. Please follow up if you find more evidence for a bug.

**Closed by beorn7** 2021-02-23 12:41 UTC
