### ISSUE TITLE
pushgateway docker container stopping time to time

### ISSUE THREAD

**Issue by AmilaDevops** [prometheus/pushgateway#407] opened 2021-06-15 10:13 UTC
@prombot  Hi friends,   I'm running prom/pushgateway:latest (version 1.4.0) as docker container in my Ubuntu linux host.  I also realized my linux host have high cpu usage of pushgateway process as well.  

My actual error is that pushgateway docker container stops everyday (it will run only 3-4 hours) with below kind of container log outputs.

log: 

level=info ts=2021-04-06T13:16:19.489Z caller=main.go:85 msg="starting pushgateway" version="(version=1.4.0, branch=HEAD, revision=007ba874bead1b9ad2253d89e3adeb16a73fd012)"
level=info ts=2021-04-06T13:16:19.489Z caller=main.go:86 build_context="(go=go1.15.7, user=root@410bc05a48f6, date=20210122-23:54:24)"
level=info ts=2021-04-06T13:16:19.492Z caller=main.go:139 listen_address=:9091
**level=info ts=2021-04-06T13:16:19.493Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
level=info ts=2021-04-16T11:10:14.272Z caller=main.go:251 msg="received SIGINT/SIGTERM; exiting gracefully..."**
level=error ts=2021-04-16T11:10:14.273Z caller=main.go:199 msg="HTTP server stopped" err="accept tcp [::]:9091: use of closed network connection"
level=info ts=2021-04-19T11:13:02.605Z caller=main.go:85 msg="starting pushgateway" version="(version=1.4.0, branch=HEAD, revision=007ba874bead1b9ad2253d89e3adeb16a73fd012)"
level=info ts=2021-04-19T11:13:02.605Z caller=main.go:86 build_context="(go=go1.15.7, user=root@410bc05a48f6, date=20210122-23:54:24)"
level=info ts=2021-04-19T11:13:02.608Z caller=main.go:139 listen_address=:9091
level=info ts=2021-04-19T11:13:02.609Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
level=error ts=2021-05-06T10:56:18.024Z caller=main.go:58 msg="error encoding and sending metric family: write tcp 172.17.0.2:9091->172.17.0.1:54710: write: broken pipe\n"
level=error ts=2021-05-29T10:33:07.421Z caller=main.go:58 msg="error encoding and sending metric family: write tcp 172.17.0.2:9091->172.17.0.1:53088: write: broken pipe\n"

**is any one have any idea why my pushgateway docker container stops ?**  

* note:  I'm running pushgateway docker container as a standalone container and it get traffic via a nginx service which running on my Ubuntu host server.  Nginx acts as a reverse proxy and input the traffic coming via external load balancers and proxy that traffic to the pushgateway docker container.

**Comment by AmilaDevops** [comment] 2021-06-21 13:02
@beorn7  can I have support above my about issue ?  thanks

**Comment by beorn7** [comment] 2021-06-21 22:16
Perhaps it consumes too much memory and therefore gets killed by Docker?

The error messages later ("broken pipe" etc.) smell like timeouts during scrapes, which could be caused by an excessive amount of metrics pushed to the Pushgateway. Note that the Pushgateway is meant for tens or hundreds of metrics, not thousands or tens of thousands.

In any case, I doubt this is a bug in Pushgateway. It seems more a problem of overload or your particular setup. I recommend to seek support via the [community channels](https://prometheus.io/community/). I'll close this, but feel free to follow up if you have more evidence pointing towards a bug.

**Closed by beorn7** 2021-06-21 22:16 UTC

**Comment by nature1995** [comment] 2023-02-05 18:31
I got the same issue.

**Comment by nature1995** [comment] 2023-02-05 18:34
* System information:
Linux 3.10.0-1062.9.1.el7.x86_64 x86_64

* Pushgateway version:
pushgateway, version 1.5.1 (branch: HEAD, revision: 7afc96cfc5e2b278f3b20e56968ff30eea22b70e)
  build user:       root@fc81889ee1a6
  build date:       20221129-16:30:38
  go version:       go1.19.3
  platform:         linux/amd64

* Pushgateway command line:
./pushgateway --web.listen-address=:9091 --web.telemetry-path=/metrics --persistence.interval=15m --persistence.file=persistence-data --push.disable-consistency-check --web.enable-admin-api --web.enable-lifecycle --log.level=info

* Logs:
```
Feb 06 01:47:11 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:47:11.281Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:34668: write: connection reset by peer\n"
Feb 06 01:48:07 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:48:07.756Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:54586: write: broken pipe\n"
Feb 06 01:48:38 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:48:38.139Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:39992: write: broken pipe\n"
Feb 06 01:49:08 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:49:08.431Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:58186: write: broken pipe\n"
Feb 06 01:49:38 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:49:38.762Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:60512: write: broken pipe\n"
Feb 06 01:50:09 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:50:09.058Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:46956: write: broken pipe\n"
Feb 06 01:50:39 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:50:39.371Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:47568: write: broken pipe\n"
Feb 06 01:51:09 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:51:09.607Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:40090: write: broken pipe\n"
Feb 06 01:51:23 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:51:23.407Z caller=diskmetricstore.go:221 level=info msg="metrics persisted" file=persistence-data
Feb 06 01:51:39 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:51:39.737Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:35444: write: broken pipe\n"
Feb 06 01:53:47 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:53:47.868Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:55806: write: connection reset by peer\n"
Feb 06 01:54:47 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T17:54:47.697Z caller=main.go:58 level=error msg="error encoding and sending metric family: write tcp 172.21.68.154:9091->172.24.44.116:43206: write: broken pipe\n"
Feb 06 02:06:17 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T18:06:17.115Z caller=diskmetricstore.go:221 level=info msg="metrics persisted" file=persistence-data
Feb 06 02:21:22 cnhb01-bdu-prod-push-gateway-3704dc pushgateway[224543]: ts=2023-02-05T18:21:22.610Z caller=diskmetricstore.go:221 level=info msg="metrics persisted" file=persistence-data
```

**Comment by beorn7** [comment] 2023-02-06 11:36
Hi @nature1995 , do you have any evidence that the issue you are seeing is caused by a bug? I have provided some ideas about what might be going on [above](https://github.com/prometheus/pushgateway/issues/407#issuecomment-865380724). Have you investigated in that direction?
