### ISSUE TITLE
`--web.route-prefix` and `--web.web.external-url` still don't work exactly like in Prometheus

### ISSUE THREAD

**Issue by siebenmann** [prometheus/pushgateway#273] opened 2019-07-23 18:04 UTC
## Bug Report
**What did you do?**

Looked at the web UI for Pushgateway 0.9.0 (in our case, this web page is behind an Apache reverse proxy).

**What did you expect to see?**

As in the 0.8.0 web UI, I expected to see icons for expanding or compacting the various pushed groups.

**What did you see instead? Under which circumstances?**

Ordinary characters instead of icons. I've attached a screenshot.

**Environment**

This has reproduced in Firefox 68.0.1 on Fedora Linux 29 and Windows 10, and Chrome 75.0.3770 on Fedora Linux 29. All environments are using uBlock Origin, but both uBlock Origin's request logger and Firefox's Network console show no blocked requests. Firefox also shows that the glyphicons-halflings-regular.woff2 font was fetched, and there are no errors in the console.

* System information:

   Pushgateway server (Ubuntu 18.04): Linux 4.15.0-52-generic x86_64

* Pushgateway version:

   ```
   pushgateway, version 0.9.0 (branch: HEAD, revision: 44d7ae6d9fb05dfe141eefb4bdf1bed7b89dee31)
     build user:       root@45c30774a08c
     build date:       20190723-15:31:55
     go version:       go1.12.7
   ```

* Pushgateway command line:

   ``/opt/prometheus/pushgateway-0.9.0.linux-amd64/pushgateway --web.listen-address=127.0.0.1:9091 --persistence.file=/var/local/prometheus/pushgateway/persist.data``

* Logs: Pushgateway is not reporting any log messages that seem relevant. The only log output since restarting with 0.9.0 is messages about persisting metrics.

Screenshot of what this looks like:
![Screenshot_2019-07-23 Prometheus Pushgateway](https://user-images.githubusercontent.com/865382/61735813-b6f5db00-ad52-11e9-80fc-7919dc91aa08.png)

**Comment by beorn7** [comment] 2019-07-23 20:50
I have seen the some once, and a deep reload (shift-F5, ctrl-F5, or whatever your browser/OS uses for a deep reload) fixed it. There are cache busters in the resource URLs now, but it still sometimes happens somehow.

**Comment by siebenmann** [comment] 2019-07-23 20:55
This happens for me even after a deep reload, and even in a browser instance that has no caches (it's a setup I use for testing, where I always want to start from a clean slate). As a double check, I started Firefox with a completely new scratch `$HOME` and still saw the problem with our Pushgateway setup.

**Comment by beorn7** [comment] 2019-07-23 21:12
Mysterious… 
I tried to reproduce:
I downloaded the `pushgateway-0.9.0.linux-amd64.tar.gz` tarball, unpacked, started the contained binary, pushed something, looked at it with Chrome 75.0.3770.142 and Firefox 68.0 on Ubuntu 19.04. All without issues.

What do you see at http://rabenste.in:9091 ?

**Comment by siebenmann** [comment] 2019-07-23 21:52
This seems to be specific to Pushgateway being behind a reverse proxy. Both your URL and our Pushgateway work if they're directly exposed, but behind a reverse proxy it malfunctions. Our reverse proxy settings predate Pushgateway's support for --web.external-url and --web.route-prefix, but when I tried to switch everything over to using those, Pushgateway generated the wrong URLs for its static assets (CSS included), which isn't an improvement. This may point to another issue.

(I copied the configuration we use for Prometheus, where we set ``--web.external-url=https://<us>/prometheus/`` and ``--web.route-prefix=/``.)

Our current Pushgateway and Apache setup uses the proxy_html module to do some minimal rewrites to make our proxying work, so perhaps that is part of the problem. I would prefer to switch over to being the same as Prometheus, which doesn't need the proxy_html stuff. (I took the Apache stuff out when I tried ``--web.external-url`` et al, then put it back in when I had to revert that.)

When I run a testing Pushgateway on a different port with the --web.* options, it generates different CSS URLs and so on than Prometheus itself does with the same arguments. The Pushgateway URLs are ``https://<us>/static/...``, which isn't going to work; they don't go through the Pushgateway URL prefix. Prometheus generates ``https://<us>/prometheus/static/...`` URLs.

**Comment by beorn7** [comment] 2019-07-23 22:16
The intended behavior of the `--web.route-prefix` and `--web.web.external-url` since Pushgateway v0.8.0 is to work exactly like the same flags of the Prometheus server. So that looks like the route of the problem. (I assume the icons weren't a problem in v0.8 because they weren't based on a specific font there.)

I'll change the title of the issue.

**Comment by siebenmann** [comment] 2019-07-23 23:50
To avoid confusion: while fixing --web.route-prefix and --web.external-url to work as they do in Prometheus will hopefully let me fix the problem in our setup by changing to use them instead of our current Apache hackery, how they work is not what's causing it now, because we're not using them in the production command line (cf the command line in my initial report).

Oh. I see what's wrong. Somehow, the characters in the bootstrap-glyphicons.min.css CSS are getting mangled when they go through our Apache reverse proxy. According to Firefox, the response on direct access has no Content-Type character set specified, but when it comes back from Apache it has a UTF-8 content-type and it looks like Apache has taken the raw UTF-8 bytes and UTF-8 encoded them again. There may be an Apache reverse proxy setting I'm missing to tell it to assume a default encoding or not re-encode character sets.

**Comment by siebenmann** [comment] 2019-07-24 18:11
For anyone who stumbles over this in the future: the root cause of our problems is that Apache 2.4's xml2enc module has a bug where it will improperly apply itself to things like text/css requests, doing character set mangling in the process. A longer discussion is here: https://www.spinics.net/lists/apache-users/msg118147.html

We don't directly use xml2enc, but we do use proxy_html to handle reverse proxying Pushgateway, and the standard Ubuntu 18.04 Apache setup drags xml2enc in because some proxy_html settings require it. We don't use those settings, and manually taking the xml2enc module out of our Apache configuration has fixed the issue.

(The better fix would be to stop using proxy_html entirely, but that needs --web.route-prefix and --web.external-url to be fixed up to work like Prometheus.)

**Comment by beorn7** [comment] 2019-07-24 21:04
Thanks for the detective work. I'll have a loot into the `--web.route-prefix` and `--web.web.external-url` at my next convenience. (If anybody beats me to it, you will be very welcome…)

**Comment by beorn7** [comment] 2019-07-25 22:20
@siebenmann could you be my guinea pig and try #274 ?
This should finally work as expected.

**Comment by siebenmann** [comment] 2019-07-26 17:25
I've now tried #274 in a copy of our production configuration, set up the same way as we have Prometheus, and everything works properly and as expected. So I think this is good.

**Comment by beorn7** [comment] 2019-07-26 22:18
Many thanks for your help. And for the good news.

**Comment by beorn7** [comment] 2019-07-30 15:51
#274 is merged now. Will be part of the next release.

**Closed** 2019-07-30 15:51 UTC
Labels: bug, help wanted
