### ISSUE TITLE
Pushgateway keep getting OOM

### ISSUE THREAD

**Issue by cosmostail** [prometheus/pushgateway#394] opened 2021-03-19 02:28 UTC
Here is the log. I'm running a 3x r5.large with 16g memory ECS cluster in a hope that it will balance out the load. But somehow, regardless how much memory I allocated to Pushgateway, it ran out of memory. 

Any idea? Thanks in advance.
```

level=info ts=2021-03-19T00:48:40.348Z caller=main.go:85 msg="starting pushgateway" version="(version=1.4.0, branch=HEAD, revision=007ba874bead1b9ad2253d89e3adeb16a73fd012)"
--
level=info ts=2021-03-19T00:48:40.349Z caller=main.go:86 build_context="(go=go1.15.7, user=root@410bc05a48f6, date=20210122-23:54:24)"
level=info ts=2021-03-19T00:48:40.350Z caller=main.go:139 listen_address=:9091
level=info ts=2021-03-19T00:48:40.350Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
level=error ts=2021-03-19T01:31:05.418Z caller=main.go:58 msg="error encoding and sending metric family: write tcp 172.17.0.2:9091->10.200.10.79:25690: write: broken pipe\n"
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0xaa3d13, 0x16)
/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc364000000, 0x4000000, 0x10977d8)
/usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x107c3c0, 0x400000, 0x7fffffffffff, 0x1c0)
/usr/local/go/src/runtime/malloc.go:727 +0x1e5
runtime.(*mheap).grow(0x107c3c0, 0x1, 0x0)
/usr/local/go/src/runtime/mheap.go:1344 +0x85
runtime.(*mheap).allocSpan(0x107c3c0, 0x1, 0x800, 0x10977e8, 0x1fe)
/usr/local/go/src/runtime/mheap.go:1160 +0x6b6
runtime.(*mheap).alloc.func1()
/usr/local/go/src/runtime/mheap.go:907 +0x65
runtime.systemstack(0x0)
/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
/usr/local/go/src/runtime/proc.go:1116
goroutine 25946 [running]:
runtime.systemstack_switch()
/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc12dedf090 sp=0xc12dedf088 pc=0x46dbe0
runtime.(*mheap).alloc(0x107c3c0, 0x1, 0x7f29585a0108, 0xc12dedf198)
/usr/local/go/src/runtime/mheap.go:901 +0x85 fp=0xc12dedf0e0 sp=0xc12dedf090 pc=0x427b25
runtime.(*mcentral).grow(0x108d078, 0x0)
/usr/local/go/src/runtime/mcentral.go:506 +0x7a fp=0xc12dedf128 sp=0xc12dedf0e0 pc=0x418d1a
runtime.(*mcentral).cacheSpan(0x108d078, 0x7f29585a1390)
/usr/local/go/src/runtime/mcentral.go:177 +0x3e5 fp=0xc12dedf1a0 sp=0xc12dedf128 pc=0x418aa5
runtime.(*mcache).refill(0x7f29b41557d0, 0x8)
/usr/local/go/src/runtime/mcache.go:142 +0xa5 fp=0xc12dedf1c0 sp=0xc12dedf1a0 pc=0x418445
runtime.(*mcache).nextFree(0x7f29b41557d0, 0xc363ffd208, 0x10, 0x8, 0xc363ffe1d8)
/usr/local/go/src/runtime/malloc.go:880 +0x8d fp=0xc12dedf1f8 sp=0xc12dedf1c0 pc=0x40d3ed
runtime.mallocgc(0x30, 0xa4f8c0, 0x101, 0x124)
/usr/local/go/src/runtime/malloc.go:1061 +0x834 fp=0xc12dedf298 sp=0xc12dedf1f8 pc=0x40ddd4
runtime.newobject(0xa4f8c0, 0xc34acaf3b0)
/usr/local/go/src/runtime/malloc.go:1195 +0x38 fp=0xc12dedf2c8 sp=0xc12dedf298 pc=0x40e278
github.com/prometheus/common/expfmt.(*TextParser).startLabelName(0xc226bc6460, 0xc363ffd220)
/app/vendor/github.com/prometheus/common/expfmt/text_parse.go:284 +0x30e fp=0xc12dedf440 sp=0xc12dedf2c8 pc=0x86a96e
github.com/prometheus/common/expfmt.(*TextParser).startLabelName-fm(0xc363ffd220)
/app/vendor/github.com/prometheus/common/expfmt/text_parse.go:267 +0x2a fp=0xc12dedf460 sp=0xc12dedf440 pc=0x86fcaa
github.com/prometheus/common/expfmt.(*TextParser).TextToMetricFamilies(0xc226bc6460, 0x7f298d2cb758, 0xc363f7c100, 0x7f298d2cb758, 0xc363f7c100, 0x0)
/app/vendor/github.com/prometheus/common/expfmt/text_parse.go:102 +0x8a fp=0xc12dedf518 sp=0xc12dedf460 pc=0x8693ea
github.com/prometheus/pushgateway/handler.Push.func1(0x7f298d4e04b8, 0xc363f68050, 0xc34abb5c00)
/app/handler/push.go:107 +0xdd6 fp=0xc12dedf788 sp=0xc12dedf518 pc=0x9610f6
net/http.HandlerFunc.ServeHTTP(0xc0004302d0, 0x7f298d4e04b8, 0xc363f68050, 0xc34abb5c00)
/usr/local/go/src/net/http/server.go:2042 +0x44 fp=0xc12dedf7b0 sp=0xc12dedf788 pc=0x6c29a4
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0xcf8ee0, 0xc0d34d90a0, 0xc34abb5c00)
/app/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:101 +0xda fp=0xc12dedf820 sp=0xc12dedf7b0 pc=0x88f7da
net/http.HandlerFunc.ServeHTTP(0xc00042e8a0, 0xcf8ee0, 0xc0d34d90a0, 0xc34abb5c00)
/usr/local/go/src/net/http/server.go:2042 +0x44 fp=0xc12dedf848 sp=0xc12dedf820 pc=0x6c29a4
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2(0xcf8ee0, 0xc0d34d90a0, 0xc34abb5c00)
/app/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:76 +0xb2 fp=0xc12dedf8d0 sp=0xc12dedf848 pc=0x88f5f2
net/http.HandlerFunc.ServeHTTP(0xc00042ea50, 0xcf8ee0, 0xc0d34d90a0, 0xc34abb5c00)
/usr/local/go/src/net/http/server.go:2042 +0x44 fp=0xc12dedf8f8 sp=0xc12dedf8d0 pc=0x6c29a4
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func2(0xcf8ee0, 0xc0d34d90a0, 0xc34abb5c00)
/app/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:172 +0x73 fp=0xc12dedf950 sp=0xc12dedf8f8 pc=0x88fb93
net/http.HandlerFunc.ServeHTTP(...)
/usr/local/go/src/net/http/server.go:2042
github.com/prometheus/pushgateway/handler.Push.func2(0xcf8ee0, 0xc0d34d90a0, 0xc34abb5c00)
/app/handler/push.go:163 +0x59 fp=0xc12dedf980 sp=0xc12dedf950 pc=0x961e99


```

**Comment by beorn7** [comment] 2021-03-21 18:39
The PGW is not really designed to run in a load-balanced setup. So I'm not sure what you are doing here to make it work.

How many metrics do you push? How large is the payload you push in this particular case?

**Comment by ssyuan** [comment] 2021-03-29 02:18
We are experiencing the same problem. We upgraded our configuration from 8G to 16G as well.
Also tried to add persistent configuration as well.
--persistence.file=". /pushdata" --persistence.interval=2m
I understand that gateway just receives the request and then forwards it to prometheus, and after successful forwarding the current request data will be released, so why will it keep taking up memory?

=======================
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xaa3d13, 0x16)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc1b4000000, 0x4000000, 0x10977d8)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x107c3c0, 0x400000, 0x42c037, 0x107c3c8)
	/usr/local/go/src/runtime/malloc.go:727 +0x1e5
runtime.(*mheap).grow(0x107c3c0, 0x6, 0x0)
	/usr/local/go/src/runtime/mheap.go:1344 +0x85
runtime.(*mheap).allocSpan(0x107c3c0, 0x6, 0x7fcff7146200, 0x10977e8, 0x7fcff7144bb8)
	/usr/local/go/src/runtime/mheap.go:1160 +0x6b6
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:907 +0x65
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1116

goroutine 49 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc0046b9810 sp=0xc0046b9808 pc=0x46dbe0
runtime.(*mheap).alloc(0x107c3c0, 0x6, 0x7fcff7400162, 0x7fcff7144bb8)
	/usr/local/go/src/runtime/mheap.go:901 +0x85 fp=0xc0046b9860 sp=0xc0046b9810 pc=0x427b25
runtime.(*mcentral).grow(0x1092a78, 0x0)
	/usr/local/go/src/runtime/mcentral.go:506 +0x7a fp=0xc0046b98a8 sp=0xc0046b9860 pc=0x418d1a
runtime.(*mcentral).cacheSpan(0x1092a78, 0x7fcff7144bb8)
	/usr/local/go/src/runtime/mcentral.go:177 +0x3e5 fp=0xc0046b9920 sp=0xc0046b98a8 pc=0x418aa5
runtime.(*mcache).refill(0x7fd0369ace98, 0x62)
	/usr/local/go/src/runtime/mcache.go:142 +0xa5 fp=0xc0046b9940 sp=0xc0046b9920 pc=0x418445
runtime.(*mcache).nextFree(0x7fd0369ace98, 0x1b62, 0x1a90, 0xa3b0a0, 0x7fcff7145301)
	/usr/local/go/src/runtime/malloc.go:880 +0x8d fp=0xc0046b9978 sp=0xc0046b9940 pc=0x40d3ed
runtime.mallocgc(0x1b00, 0xa3b0a0, 0xc1b3847501, 0xc1b3f78200)
	/usr/local/go/src/runtime/malloc.go:1061 +0x834 fp=0xc0046b9a18 sp=0xc0046b9978 pc=0x40ddd4
runtime.newarray(0xa3b0a0, 0x11, 0xa6e060)
	/usr/local/go/src/runtime/malloc.go:1217 +0x65 fp=0xc0046b9a48 sp=0xc0046b9a18 pc=0x40e305
runtime.makeBucketArray(0x9fbe60, 0xc1b3849a04, 0x0, 0xc00ac02a58, 0xc00028a960)
	/usr/local/go/src/runtime/map.go:362 +0x199 fp=0xc0046b9a80 sp=0xc0046b9a48 pc=0x40f299
runtime.makemap(0x9fbe60, 0x40, 0xc1b3849a10, 0x32)
	/usr/local/go/src/runtime/map.go:328 +0xf4 fp=0xc0046b9ac8 sp=0xc0046b9a80 pc=0x40f014
github.com/prometheus/pushgateway/storage.(*DiskMetricStore).GetMetricFamiliesMap(0xc00005b920, 0x0)
	/app/storage/diskmetricstore.go:195 +0x265 fp=0xc0046b9c28 sp=0xc0046b9ac8 pc=0x958e45
github.com/prometheus/pushgateway/storage.(*DiskMetricStore).checkWriteRequest(0xc00005b920, 0xc0bcce3410, 0xc00ff7b7c5a5e544, 0x6e6d9dc439d, 0x1064660, 0xc0bcce3470, 0x1, 0xc0bc100180, 0x449b00)
	/app/storage/diskmetricstore.go:375 +0x1b7 fp=0xc0046b9d68 sp=0xc0046b9c28 pc=0x95a237
github.com/prometheus/pushgateway/storage.(*DiskMetricStore).loop(0xc00005b920, 0x45d964b800)
	/app/storage/diskmetricstore.go:233 +0x4b5 fp=0xc0046b9fd0 sp=0xc0046b9d68 pc=0x959475
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0046b9fd8 sp=0xc0046b9fd0 pc=0x46f821
created by github.com/prometheus/pushgateway/storage.NewDiskMetricStore
	/app/storage/diskmetricstore.go:103 +0x1e6

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7fd00fd1fe88, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000143418, 0x72, 0x0, 0x0, 0xa999ba)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000143400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:394 +0x1fc
net.(*netFD).accept(0xc000143400, 0xb55232fe2627aa, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0002aff20, 0x605f6965, 0xc0004cb818, 0x4c7aa6)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0002aff20, 0xc0004cb868, 0x18, 0xc000000300, 0x6c656c)
	/usr/local/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc0002cc000, 0xcf8c60, 0xc0002aff20, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2937 +0x266
github.com/prometheus/exporter-toolkit/web.Serve(0xcf8c60, 0xc0002aff20, 0xc0002cc000, 0x0, 0x0, 0xcee5e0, 0xc00028a5d0, 0x0, 0xc00028a5d0)
	/app/vendor/github.com/prometheus/exporter-toolkit/web/tls_config.go:192 +0x1b0
main.main()
	/app/main.go:198 +0x36a8

**Comment by beorn7** [comment] 2021-03-29 12:01
The PGW does not forward anything to Prometheus. Prometheus is pull based, so the PGW stores all the pushed metrics and presents them to scrapers (like the Prometheus server) until deleted or overwritten. Thus, if you push a lot of metrics, the PGW will use a lot of memory. That's why I asked how many metrics are in that particular push request, and how many are on the PGW in total.

It should be noted that the PGW is not designed as an efficient bulk metric storage. It's meant for tens to hundreds of metrics. It might still work with thousands, but barely so.

If you run into trouble going beyond that, it's not a bug, it's by design.

**Comment by beorn7** [comment] 2021-04-12 20:21
Assuming my comment clarified the issue.

**Closed by beorn7** 2021-04-12 20:21 UTC
