### ISSUE TITLE
Got 400 Bad Request while sending metrics generated by Telegraf

### ISSUE THREAD

**Issue by brightzheng100** [prometheus/pushgateway#275] opened 2019-07-30 11:29 UTC
## Bug Report

**What did you do?**

I used `Telegraf`'s `http` output plugin, trying to send metrics to pushgateway but I kept getting `400 Bad Request` error.

Then I tried to simply use `curl` to send and found that the error message was clear: `text format parsing error in line 31: second HELP line for metric name "cpu_usage_irq"`.

So looks like the metrics were invalid. 

> Note: I rebuilt the Telegraf by using this [PR](https://github.com/influxdata/telegraf/pull/5427) as it supports `Prometheus` format.

Could you advise what prerequisites we need to meet while sending over to pushgateway?

Attached were the metrics with line number (so that you can easily point out why line 31 is wrong):
```
  1 # HELP cpu_usage_idle Telegraf collected metric
  2 # TYPE cpu_usage_idle gauge
  3 cpu_usage_idle{cpu="cpu-total",host="Brights-MacBook-Pro.local"} 86.7759289378206
  4 # HELP cpu_usage_guest Telegraf collected metric
  5 # TYPE cpu_usage_guest gauge
  6 cpu_usage_guest{cpu="cpu-total",host="Brights-MacBook-Pro.local"} 0
  7 # HELP cpu_usage_user Telegraf collected metric
  8 # TYPE cpu_usage_user gauge
  9 cpu_usage_user{cpu="cpu-total",host="Brights-MacBook-Pro.local"} 7.694232453396722
 10 # HELP cpu_usage_nice Telegraf collected metric
 11 # TYPE cpu_usage_nice gauge
 12 cpu_usage_nice{cpu="cpu-total",host="Brights-MacBook-Pro.local"} 0
 13 # HELP cpu_usage_steal Telegraf collected metric
 14 # TYPE cpu_usage_steal gauge
 15 cpu_usage_steal{host="Brights-MacBook-Pro.local",cpu="cpu-total"} 0
 16 # HELP cpu_usage_softirq Telegraf collected metric
 17 # TYPE cpu_usage_softirq gauge
 18 cpu_usage_softirq{cpu="cpu-total",host="Brights-MacBook-Pro.local"} 0
 19 # HELP cpu_usage_system Telegraf collected metric
 20 # TYPE cpu_usage_system gauge
 21 cpu_usage_system{cpu="cpu-total",host="Brights-MacBook-Pro.local"} 5.5298386087826845
 22 # HELP cpu_usage_iowait Telegraf collected metric
 23 # TYPE cpu_usage_iowait gauge
 24 cpu_usage_iowait{cpu="cpu-total",host="Brights-MacBook-Pro.local"} 0
 25 # HELP cpu_usage_irq Telegraf collected metric
 26 # TYPE cpu_usage_irq gauge
 27 cpu_usage_irq{cpu="cpu-total",host="Brights-MacBook-Pro.local"} 0
 28 # HELP cpu_usage_guest_nice Telegraf collected metric
 29 # TYPE cpu_usage_guest_nice gauge
 30 cpu_usage_guest_nice{cpu="cpu-total",host="Brights-MacBook-Pro.local"} 0
 31 # HELP cpu_usage_irq Telegraf collected metric
 32 # TYPE cpu_usage_irq gauge
 33 cpu_usage_irq{cpu="cpu-total",host="Brights-MacBook-Pro.local"} 0
```

**What did you expect to see?**

Whatever metrics generated by `Telegraf`, just send them over to pushgateway.

**What did you see instead? Under which circumstances?**

`400 Bad Request` because of the text format parsing error 

**Environment**

```
OS: Linux version 4.15.0-54-generic (buildd@lgw01-amd64-039) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019

pushgateway version: 0.8.0
```

* System information:

```
Linux 4.15.0-54-generic x86_64
```

* Pushgateway version:

```
  build user:       root@00855c3ed64f
  build date:       20190413-11:29:19
  go version:       go1.11.8
```

* Pushgateway command line:

```
pushgateway --persistence.file=/var/vcap/store/pushgateway/pushgateway.metrics --web.listen-address=:9091
```

* Logs:

```
No special error logs found.
```

**Comment by beorn7** [comment] 2019-07-30 12:07
Thanks for the comprehensive bug report.

The problem is that lines 31–33 are a verbatim repetition of lines 25–27. One of them has to go.

This is clearly a bug in Telegraf. It doesn't generate proper Prometheus text format. See its [specification](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format).

I'm closing this issue here. Please get in touch with those responsible for the relevant code in Telegraf.

**Closed by beorn7** 2019-07-30 12:07 UTC
