### ISSUE TITLE
Reject inconsistent metrics at push time (and create a synthetic metric about it)

### ISSUE THREAD

**Issue by fvigotti** [prometheus/pushgateway#202] opened 2018-09-13 14:29 UTC
and instead it should log the malformed data that has received and then discard it..
thre is already an issue in collectd exporter.. and I've already discussed it there  
https://github.com/prometheus/collectd_exporter/issues/56#issuecomment-419131935

I have no skill in go and zero time to help, sorry :(

**Comment by fvigotti** [comment] 2018-09-14 06:58
Hi @beorn7 , In understand that could be quite invasive , but having the whole application file to return metrics ( maybe some thousands of metrics ) because one of hundreds endpoint sent an invalid one it's a wrong behaviour, if you or other pushgateway developer are worried about performance or being too invasive change, let's user enable it with a arg-flag...
I don't know the internals.. but O(n²)  seems **a lot** to me.. ther eare no way to check validity of incoming data which is cheaper ?

**Comment by beorn7** [comment] 2018-09-14 09:36
First of all, if you have thousands of metrics on your PGW, the odds are you are using it wrong. See https://prometheus.io/docs/practices/pushing/ .

The PGW is fairly light-weight. In general, I would recommend to us one per team or service needing it. In that way, collisions of metrics are less likely, and a failure won't affect larger groups.

About the O(n²): This is just in the nature of the problem. Checking if the total exposition the PGW would offer to scrape is consistent is broadly proportional to the number of metrics pushed. Also, the check has to be performed on each push. Thus, if you double the number of pushers, you double the number of checks, and each check takes twice as long as double the metrics are pushed. Computational effort is now increased by a factor of four. One might improve this with some hash tables tracking the already pushed metrics, but it makes the code even more involved.

In any case, a rejected push needed to be represented in the scrape in _some_ way. You must be able to alert on it.

**Comment by beorn7** [comment] 2018-09-14 14:12
#94 is related but more concerned with the way how to handle the case if inconsistent metrics have made it into the Pushgateway. If this issue results in not letting this happen in the first place, #94 would be obsolete.

**Comment by rombie** [comment] 2019-08-04 04:42
Is there any update on this ? I tried with the latest version available now (0.9.1) but get the same set of errors. I do not understand the logic at all as to why /metrics get has to fail... it is the push that should fail, not get. Other option is to provide a get end-point. If so, then clients can call get before attempting the push... (I still don't udnerstand what O(n^2) referred to here..). Please do not fail GET on /metrics. Scraping will stop working due to this issue (and it was working few months ago)

**Comment by beorn7** [comment] 2019-08-12 17:26
The state is that the problem is well understood and a solution is sketched out in my head.
Actually implementing it is pretty high up on my list. This _may_ mean it will happen this week, but I cannot promise anything.

**Comment by rombie** [comment] 2019-09-19 21:44
Thanks so much. I very much appreciate it!

**Comment by beorn7** [comment] 2019-09-20 16:38
Fix is in master. Will be released once #287 is done. But please feel free to build from master and try it out. It's a fairly invasive change, and some pre-release feedback will be appreciated.

**Closed by beorn7** 2019-09-20 16:38 UTC
Labels: feature request, not-as-easy-as-it-looks
