### ISSUE TITLE
pushgateway suffered an OOM

### ISSUE THREAD

**Issue by qiangmzsx** [prometheus/pushgateway#566] opened 2023-07-24 07:13 UTC
I hope this message finds you well. I am writing to report an issue I encountered while integrating Flink monitoring with the Prometheus Pushgateway.

Issue Description:
After running Flink with the Prometheus Pushgateway integration for some time, I noticed that the memory usage of the Pushgateway significantly increases, eventually leading to Out of Memory (OOM) errors. My server configuration consists of 4 cores and 8GB RAM.

Steps to Reproduce:

    Deploy Prometheus Pushgateway with the specified server configuration (4 cores, 8GB RAM).
    Integrate Flink monitoring with the Pushgateway.
    Monitor the memory usage over time during Flink job executions.

Expected Behavior:
The memory usage of the Pushgateway should remain stable and not cause any significant memory growth.

Actual Behavior:
The memory consumption of the Pushgateway increases continuously, leading to OOM situations.

![image](https://github.com/prometheus/pushgateway/assets/4846144/b43a6b88-c257-4683-aa44-e19ca92b4c08)

**Comment by dmsolr** [comment] 2023-07-25 07:29
Hello, @qiangmzsx 
There is the same issue from me.
I am very confuse why the pgw memory usage grows regularly until oom. 
and there are stable metrics with almost fixed cardinal in my scenarios.
it is a counter intuition thing what the seem like the pushed metrics data remain permanently in PGW memory.

**Comment by qiangmzsx** [comment] 2023-07-25 08:45
> Hello, @qiangmzsx There is the same issue from me. I am very confuse why the pgw memory usage grows regularly until oom. and there are stable metrics with almost fixed cardinal in my scenarios. it is a counter intuition thing what the seem like the pushed metrics data remain permanently in PGW memory.

I used pprof to monitor the heap information prior to OOM, and I don't think it's the metrics that are hogging the content, but rather what bug was triggered in the parsing of the metrics information pushed over that caused the memory spike.
1. we have four machines, but every few days one goes OOM and the other three are normal. I originally thought it was unbalanced traffic, and after adding logs and network monitoring I found that the traffic was balanced.
2. pprof's monitoring shows that bytes.Buffer's String() function is taking up a lot of memory space. This is unreasonable, why is the memory not being freed?

**Comment by dmsolr** [comment] 2023-07-25 12:52
Thanks for your sharing.

so strange. it has been working well util few day ago. And then the first OOM caused by a bug that due to a metrics with high-cardinal issue. but PGW still triggers oom regularly, even though it has been fixed.

**Comment by beorn7** [comment] 2023-07-25 16:12
Happy to accept PRs that optimize the memory consumption of the Pushgateway.

I don't think that there's a recent regression, as no substantial code changes have happened in a while. But if you can see a regression between Pushgateway versions, I would like to hear about it.

Note that the Pushgateway is not designed for heavy lifting. The intended use case is essentially a hand full of metrics in a single push and maybe hundreds of metrics on the PGW at the same time. If you OOM because of parsing the pushed payload, I would assume you are pushing really large amounts of metrics.

**Comment by TyroneMax** [comment] 2023-12-01 09:34
Hello, @qiangmzsx 
There is the same issue from me.
According to his statement, this issue is caused by too many indicators for a single PGW instance. Therefore, our company has adopted the method of pushing indicators for different services to different instances and  and then Prometheus pulls them uniformly. Our own experiments have found that a single 8C 16GB instance can store approximately 40000 indicators.

We also used nginx for routing forwarding, which facilitates our subsequent migration of metrics to other instances.

**Comment by beorn7** [comment] 2024-01-06 22:33
As this doesn't appear to be a bug in the PGW, I'm closing the issue.

**Closed by beorn7** 2024-01-06 22:33 UTC
