### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by kapitani4** [prometheus/pushgateway#676] opened 2024-08-26 12:55 UTC
I used Fluent-bit Prometheus Remote Write plugin, trying to send metrics to pushgateway from Node Exporter but I kept getting 400 Bad Request error.

[OUTPUT]
    Name                 prometheus_remote_write
    Match                node_metrics
    Host                 example.com
    Port                 443
    Uri                  pushgateway/metrics/job/<servername>
    Tls                  On
    Tls.verify           Off
    log_response_payload true

I use this configuration as I want to send metrics to prometheus via pushgateway from multiple servers, to keep the metrics from getting mixed up, I send in metrics by server name in the job 

Then I tried to simply use curl to send and found that the error message was clear

So looks like the metrics were invalid.

Could you advise what prerequisites we need to meet while sending over to pushgateway?

**Comment by beorn7** [comment] 2024-08-28 14:52
The Pushgateway receives the Prometheus exposition format, not the Prometheus remote-write format.

If need be, you can send metrics via remote-write directly to your Prometheus server (although that has to be used with caution).

Closing, as this is not a bug.

If you have further questions, please use the community channels listed in https://prometheus.io/community/

**Closed by beorn7** 2024-08-28 14:52 UTC
