### ISSUE TITLE
Performance issues after 0.9.1

### ISSUE THREAD

**Issue by BirknerAlex** [prometheus/pushgateway#321] opened 2020-01-23 08:56 UTC
## Bug Report

**What did you do?**
I've upgraded from 0.9.1 to 1.0.1. After having issues I tested also 0.10.0 and 1.0.0.

**What did you expect to see?**
Same or better performance as with 0.9.1 before. 

**What did you see instead? Under which circumstances?**

With 0.10.0 or higher I've seen long (30 sec+) or failing requests under high load of the pushgateway.

The pushgatway recieves around 300 req/s, with 0.9.1 it wasn't a problem at all. With downgrading to 0.9.1 the problem is immediately resolved (reproduceable). 

With `strace` I saw the process waiting for a Mutex for multiple seconds again and again. 

**Environment**

* System information:

		Linux 4.18.0-147.3.1.el8_1.x86_64 x86_64

* Pushgateway version:

		0.10.0, 1.0.0, 1.0.1
                
* Pushgateway command line:

		/usr/local/bin/prometheus-pushgateway

* Logs:
```
Jan 22 14:49:10 xxxxxxxxx prometheus-pushgateway[12359]: level=info ts=2020-01-22T14:49:10.690Z caller=main.go:81 msg="starting pushgateway" version="(version=1.0.1, branch=HEAD, revision=793293bdadd51fdaca69de5bb25637b0f93b656b)"
Jan 22 14:49:10 xxxxxxxxx prometheus-pushgateway[12359]: level=info ts=2020-01-22T14:49:10.690Z caller=main.go:82 build_context="(go=go1.13.5, user=prom@0489a6432d5d, date=20191220-22:39:32)"
Jan 22 14:49:10 xxxxxxxxx prometheus-pushgateway[12359]: level=info ts=2020-01-22T14:49:10.691Z caller=main.go:142 listen_address=:9091
```

**Comment by beorn7** [comment] 2020-01-24 00:29
Duplicate of #313 . If you build from master, you will have a flag to disable the checks that cause the degraded performance.

Also note that you are probably not using the PGW for what it is meant to be used for, see #313 for details.

I plan to cut a new release in the next few days so that you'll also get pre-built binaries.

**Closed by beorn7** 2020-01-24 00:29 UTC
Labels: duplicate

**Comment by BirknerAlex** [comment] 2020-01-24 10:47
Sorry, I didn't checked the closed issues for duplicates. 

Also I know I am using PGW in a "wrong way", I am currently working on re-implementing the Prometheus monitoring but it was the easiest way to replace my statsd implementation to use Prometheus.

But thanks for your awesome work and response! :)

**Comment by brian-brazil** [comment] 2020-01-24 10:50
There is https://github.com/prometheus/statsd_exporter
