### ISSUE TITLE
Feature request: get to confirm if metric instance information exists

### ISSUE THREAD

**Issue by Ohen** [prometheus/pushgateway#140] opened 2017-11-28 08:58 UTC
Hi, guys 

I think `pushgateway` need to `get method` that confirm if metric instance information exists.
because, Make sure that the metric instance information does not exist ttl is not supported by pushgateway, so we are deleting the value using delete.

however, in the case of delete, it is just retrun to 202(accepted). It can not be guaranteed that it has been deleted. 

as a result of looking at the code, I noticed that pushgateway can not give a success when I delete it. because pushgateway put it in a queue.

however, the pushgateway seems necessary guarantee deletion via the get method for instance. 

please, discuss this with your team.

Thanks

**Comment by beorn7** [comment] 2017-11-29 12:12
I'm not sure i understand what you are fishing for here.

The Pushgateway is not a consistent data storage with any guarantees (ACID or anything else). It's all best effort by design.

Having said that, it's very unlikely that a delete doesn't succeed. Or, in other words, the cases where it fails are so serious that even any kind of success code wouldn't really help. For example, let's imagine the Pushgateway successfully deletes the metric from its internal storage and confirms that to the user. Then the whole server crashes before the mutation of the storage is properly persisted to disk. After the restart, the old state comes from the disk, and your "deleted" metric is back and alive.

About the GET method to learn about metrics on the Pushgateway: The `/metrics` endpoint gives you exactly that. You can even pick from text format and protobuf format. And if you really need JSON, have a look at https://github.com/prometheus/prom2json

**Comment by beorn7** [comment] 2018-02-12 18:16
Closing due to unresponsiveness.

**Closed by beorn7** 2018-02-12 18:16 UTC
