### ISSUE TITLE
A simple way to make PushGateway always return 500

### ISSUE THREAD

**Issue by wfhu** [prometheus/pushgateway#214] opened 2018-10-11 10:06 UTC
## Bug Report
**What did you do?**
When  I use shell to send redundent metrics to pushgateway service via HTTP request, the pushgateway become unusable, because it will always return 500 Internel  Server Error

The normal scripts looks like this:

    cat <<EOF | curl --data-binary @-http://172.19.58.106:9091/metrics/job/huwf_job/instance/172.19.58.106
    # TYPE some_metric counter
    some_metric{label="val1"} 42
    # TYPE another_metric gauge
    # HELP another_metric Just an example.
    another_metric 2398.283

The above script is absolutely fine. But when I add one more line, and run it, the PushGateway will have problem.

The BAD scripts looks like this:

    cat <<EOF | curl --data-binary @- http://172.19.58.106:9091/metrics/job/huwf_job/instance/172.19.58.106
    # TYPE some_metric counter
    some_metric{label="val1"} 42
    some_metric{label="val1"} 42
    # TYPE another_metric gauge
    # HELP another_metric Just an example.
    another_metric 2398.283

Please notice there are two same metrics-labels combination.
After I run the BAD script, the pushgateway become unusable. I have to restart the pushgateway process.

**What did you expect to see?**
This is like some kind of DoS attach, because anyone with access to the pushgateway service will be able to make it unusable. 
I think the pushgateway process should detect this kind of problem, and not become unusable. I think it would be fine to just report error to client and reject the data, or show a warning message and take the last pushed data.

**What did you see instead? Under which circumstances?**
The pushgateway become ususable.

The error log of Prometheus:

> level=debug ts=2018-10-11T08:20:55.640547371Z caller=scrape.go:687 component="scrape manager" scrape_pool=pushgateway target=http://127.0.0.1:9091/metrics msg="Scrape failed" err="server returned HTTP status 500 Internal Server Error"
level=debug ts=2018-10-11T08:21:25.631180199Z caller=scrape.go:687 component="scrape manager" scrape_pool=pushgateway target=http://127.0.0.1:9091/metrics msg="Scrape failed" err="server returned HTTP status 500 Internal Server Error"
level=debug ts=2018-10-11T08:21:55.625134532Z caller=scrape.go:687 component="scrape manager" scrape_pool=pushgateway target=http://127.0.0.1:9091/metrics msg="Scrape failed" err="server returned HTTP status 500 Internal Server Error"
level=debug ts=2018-10-11T08:22:25.615441221Z caller=scrape.go:687 component="scrape manager" scrape_pool=pushgateway target=http://127.0.0.1:9091/metrics msg="Scrape failed" err="server returned HTTP status 500 Internal Server Error"
level=debug ts=2018-10-11T08:22:55.618985952Z caller=scrape.go:687 component="scrape manager" scrape_pool=pushgateway target=http://127.0.0.1:9091/metrics msg="Scrape failed" err="server returned HTTP status 500 Internal Server Error"
level=debug ts=2018-10-11T08:23:25.613090781Z caller=scrape.go:687 component="scrape manager" scrape_pool=pushgateway target=http://127.0.0.1:9091/metrics msg="Scrape failed" err="server returned HTTP status 500 Internal Server Error"

**Environment**

* System information:

CentOS Linux release 7.5.1804 (Core)
Linux 3.10.0-862.2.3.el7.x86_64 x86_64

* Pushgateway version:

pushgateway, version 0.5.2 (branch: HEAD, revision: 231071b3e0a57b58df717bba5f4e5d88cac95389)
  build user:       root@c95e387ff56a
  build date:       20180615-16:11:56
  go version:       go1.10.3

prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10

* Pushgateway command line:

	/opt/push/pushgateway/bin/pushgateway --web.listen-address=:9091 --log.level=debug

* Logs:
```
The pushgateway error log:

time="2018-10-11T16:17:11+08:00" level=debug msg="Failed to parse text, text format parsing error in line 1: expected float as value, got \"\"" source="push.go:108"
time="2018-10-11T16:18:11+08:00" level=debug msg="Failed to parse text, text format parsing error in line 1: expected float as value, got \"\"" source="push.go:108"
time="2018-10-11T16:19:12+08:00" level=debug msg="Failed to parse text, text format parsing error in line 1: expected float as value, got \"\"" source="push.go:108"
time="2018-10-11T16:20:11+08:00" level=debug msg="Failed to parse text, text format parsing error in line 1: expected float as value, got \"\"" source="push.go:108"
time="2018-10-11T16:21:11+08:00" level=debug msg="Failed to parse text, text format parsing error in line 1: expected float as value, got \"\"" source="push.go:108"
time="2018-10-11T16:22:11+08:00" level=debug msg="Failed to parse text, text format parsing error in line 1: expected float as value, got \"\"" source="push.go:108"
time="2018-10-11T16:23:11+08:00" level=debug msg="Failed to parse text, text format parsing error in line 1: expected float as value, got \"\"" source="push.go:108"
```

**Comment by beorn7** [comment] 2018-10-11 10:44
This is a dupe of https://github.com/prometheus/pushgateway/issues/202

**Closed by beorn7** 2018-10-11 10:44 UTC
